language: scala

scala:
  - 2.12.8
  - 2.13.0

jdk:
  - oraclejdk8
  - openjdk8
  - openjdk11

matrix:
  allow_failures:
    - scala: 2.13.0
      jdk: oraclejdk8
    - scala: 2.13.0
      jdk: openjdk8
    - scala: 2.13.0
      jdk: openjdk11

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
